### ISSUE TITLE
test_dataset option with wals

### ISSUE THREAD

**Issue by rpagliarix** [quora/qmf#5]
is test_dataset not available with wals, or is it missing from the dodumentation?

**Comment by sbourke** [comment]
Seems to be here - https://github.com/quora/qmf/blob/3b0e3831c12fd0b21f4e9792183442b4fec6c949/qmf/wals.cpp#L37 What problem are you having ?

**Comment by rpagliarix** [comment]
no problem, but it is missing in the README.

Thank you for clarifying
